apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
  namespace: keda-demo
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-myqueue
    key: servicebus-connectionstring
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: keda-demo
spec:
  scaleTargetRef:
    deploymentName: order-processor
  pollingInterval: 2 # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Change to define how many minimum replicas you want
  maxReplicaCount: 7
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true       # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 15
          policies:
          - type: Percent
            value: 100
            periodSeconds: 5
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: myqueue
      queueLength: "5" # default 5
    authenticationRef:
        name: azure-servicebus-auth # authenticationRef would need either podIdentity or define a connection parameter